# Generated by Django 3.2.25 on 2024-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Text',
            field=models.CharField(max_length=500),
        ),
    ]
