# Generated by Django 3.2.25 on 2024-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_todo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Ticked',
            field=models.BooleanField(default=False),
        ),
    ]
